# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(
        regex="^chart/~create/$",
        view=views.chartCreateView.as_view(),
        name='chart_create',
    ),
    url(
        regex="^chart/(?P<pk>\d+)/~delete/$",
        view=views.chartDeleteView.as_view(),
        name='chart_delete',
    ),
    url(
        regex="^chart/(?P<pk>\d+)/$",
        view=views.chartDetailView.as_view(),
        name='chart_detail',
    ),
    url(
        regex="^chart/(?P<pk>\d+)/~update/$",
        view=views.chartUpdateView.as_view(),
        name='chart_update',
    ),
    url(
        regex="^chart/$",
        view=views.chartListView.as_view(),
        name='chart_list',
    ),
	url(
        regex="^data/~create/$",
        view=views.dataCreateView.as_view(),
        name='data_create',
    ),
    url(
        regex="^data/(?P<pk>\d+)/~delete/$",
        view=views.dataDeleteView.as_view(),
        name='data_delete',
    ),
    url(
        regex="^data/(?P<pk>\d+)/$",
        view=views.dataDetailView.as_view(),
        name='data_detail',
    ),
    url(
        regex="^data/(?P<pk>\d+)/~update/$",
        view=views.dataUpdateView.as_view(),
        name='data_update',
    ),
    url(
        regex="^data/$",
        view=views.dataListView.as_view(),
        name='data_list',
    ),
	url(
        regex="^config/~create/$",
        view=views.configCreateView.as_view(),
        name='config_create',
    ),
    url(
        regex="^config/(?P<pk>\d+)/~delete/$",
        view=views.configDeleteView.as_view(),
        name='config_delete',
    ),
    url(
        regex="^config/(?P<pk>\d+)/$",
        view=views.configDetailView.as_view(),
        name='config_detail',
    ),
    url(
        regex="^config/(?P<pk>\d+)/~update/$",
        view=views.configUpdateView.as_view(),
        name='config_update',
    ),
    url(
        regex="^config/$",
        view=views.configListView.as_view(),
        name='config_list',
    ),
	]
